const ADD_USER = 'ADD_USER';
const REMOVE_USER = 'REMOVE_USER';
const UPDATE_ROOM_USERS = 'UPDATE_ROOM_USERS';
const REMOVE_ROOM_USERS = 'REMOVE_ROOM_USERS';
const ADD_ROOM_MESSAGE = 'ADD_ROOM_MESSAGE';
const CREATE_ROOM = 'CREATE_ROOM';
const ADD_USER_ROOM = 'ADD_USER_ROOM';
const REMOVE_USER_ROOM = 'REMOVE_USER_ROOM';


module.exports = {
  ADD_USER,
  REMOVE_USER,
  UPDATE_ROOM_USERS,
  REMOVE_ROOM_USERS,
  ADD_ROOM_MESSAGE,
  CREATE_ROOM,
  ADD_USER_ROOM,
  REMOVE_USER_ROOM,
};